export const BORDER_RADIUS = 'BORDER_RADIUS';
export const PADDING = 'PADDING';
export const PADDING_UNIT = 'PADDING_UNIT';
export const PADDING_VERTICAL = 'PADDING_VERTICAL';
export const PADDING_VERTICAL_UNIT = 'PADDING_VERTICAL_UNIT';
export const PADDING_HORIZONTAL = 'PADDING_HORIZONTAL';
export const PADDING_HORIZONTAL_UNIT = 'PADDING_HORIZONTAL_UNIT';
export const PADDING_LINKED_SIDES = 'PADDING_LINKED_SIDES';


