export const BORDER_RADIUS = 'BORDER_RADIUS';
export const PADDING = 'PADDING';
export const PADDING_UNIT = 'PADDING_UNIT';
export const PADDING_VERTICAL = 'PADDING_VERTICAL';
export const PADDING_VERTICAL_PX = 'PADDING_VERTICAL_PX';
export const PADDING_VERTICAL_EM = 'PADDING_VERTICAL_EM';
export const PADDING_HORIZONTAL = 'PADDING_HORIZONTAL';
export const PADDING_HORIZONTAL_PX = 'PADDING_HORIZONTAL_PX';
export const PADDING_HORIZONTAL_EM = 'PADDING_HORIZONTAL_EM';


